apiVersion: v1
kind: Service
metadata:
  name: lovebridge-service
  labels:
    app: lovebridge
spec:
  selector:
    app: lovebridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer